[package]
name = "bevy-inspector-egui-rapier"
version = "0.1.0"
edition = "2021"

[features]
rapier3d = ["bevy_rapier3d"]
rapier2d = ["bevy_rapier2d"]

[dependencies]
bevy-inspector-egui = { version = "0.7", path = "../..", features = ["nalgebra030"] }
bevy_rapier3d = { version = "0.12.0", optional = true }
bevy_rapier2d = { version = "0.12.0", optional = true }
bevy = { version = "0.6", default-features = false }

[dev-dependencies]
bevy = { version = "0.6", default-features = false, features = ["x11", "bevy_winit"] }

[[example]]
name = "rapier2d"
required-features = ["rapier2d"]

[[example]]
name = "rapier3d"
required-features = ["rapier3d"]